[2023-06-18 21:00:44,676] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Postgres_airflow_connection_test_v01.insert_weather_data 2023-06-17T00:00:00+00:00 [queued]>
[2023-06-18 21:00:44,686] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Postgres_airflow_connection_test_v01.insert_weather_data 2023-06-17T00:00:00+00:00 [queued]>
[2023-06-18 21:00:44,687] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-06-18 21:00:44,688] {taskinstance.py:1043} INFO - Starting attempt 3 of 3
[2023-06-18 21:00:44,689] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-06-18 21:00:44,702] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): insert_weather_data> on 2023-06-17T00:00:00+00:00
[2023-06-18 21:00:44,706] {standard_task_runner.py:52} INFO - Started process 894 to run task
[2023-06-18 21:00:44,711] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Postgres_airflow_connection_test_v01', 'insert_weather_data', '2023-06-17T00:00:00+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpe0is5wf4', '--error-file', '/tmp/tmp1od7pkmr']
[2023-06-18 21:00:44,715] {standard_task_runner.py:77} INFO - Job 8: Subtask insert_weather_data
[2023-06-18 21:00:44,763] {logging_mixin.py:104} INFO - Running <TaskInstance: Postgres_airflow_connection_test_v01.insert_weather_data 2023-06-17T00:00:00+00:00 [running]> on host ac1bf3331ec5
[2023-06-18 21:00:44,804] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Servin
AIRFLOW_CTX_DAG_ID=Postgres_airflow_connection_test_v01
AIRFLOW_CTX_TASK_ID=insert_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-17T00:00:00+00:00
[2023-06-18 21:00:44,806] {postgres.py:69} INFO - Executing: 
            INSERT INTO 
            master_weather(forecast_date, city, state, max_temp, min_temp) 
            VALUES 
                (CURRENT_DATE, 'Houston', 'TX', 101, 79),
                (CURRENT_DATE, 'Dallas', 'TX', 98, 75);
        
[2023-06-18 21:00:44,816] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: airflow, Login: airflow, Password: XXXXXXXX, extra: None
[2023-06-18 21:00:44,824] {dbapi.py:180} INFO - Running statement: 
            INSERT INTO 
            master_weather(forecast_date, city, state, max_temp, min_temp) 
            VALUES 
                (CURRENT_DATE, 'Houston', 'TX', 101, 79),
                (CURRENT_DATE, 'Dallas', 'TX', 98, 75);
        , parameters: None
[2023-06-18 21:00:44,830] {dbapi.py:186} INFO - Rows affected: 2
[2023-06-18 21:00:44,841] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=Postgres_airflow_connection_test_v01, task_id=insert_weather_data, execution_date=20230617T000000, start_date=20230618T210044, end_date=20230618T210044
[2023-06-18 21:00:44,865] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-18 21:00:44,883] {local_task_job.py:146} INFO - Task exited with return code 0
