[2023-06-18 21:00:43,830] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Postgres_airflow_connection_test_v01.create_weather_table 2023-06-17T00:00:00+00:00 [queued]>
[2023-06-18 21:00:43,847] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: Postgres_airflow_connection_test_v01.create_weather_table 2023-06-17T00:00:00+00:00 [queued]>
[2023-06-18 21:00:43,849] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-06-18 21:00:43,850] {taskinstance.py:1043} INFO - Starting attempt 3 of 3
[2023-06-18 21:00:43,851] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-06-18 21:00:43,861] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_weather_table> on 2023-06-17T00:00:00+00:00
[2023-06-18 21:00:43,866] {standard_task_runner.py:52} INFO - Started process 892 to run task
[2023-06-18 21:00:43,870] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Postgres_airflow_connection_test_v01', 'create_weather_table', '2023-06-17T00:00:00+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpi38hl1bc', '--error-file', '/tmp/tmpy2nrodi1']
[2023-06-18 21:00:43,875] {standard_task_runner.py:77} INFO - Job 7: Subtask create_weather_table
[2023-06-18 21:00:43,925] {logging_mixin.py:104} INFO - Running <TaskInstance: Postgres_airflow_connection_test_v01.create_weather_table 2023-06-17T00:00:00+00:00 [running]> on host ac1bf3331ec5
[2023-06-18 21:00:43,965] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Servin
AIRFLOW_CTX_DAG_ID=Postgres_airflow_connection_test_v01
AIRFLOW_CTX_TASK_ID=create_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-17T00:00:00+00:00
[2023-06-18 21:00:43,967] {postgres.py:69} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS master_weather (
            weather_id SERIAL PRIMARY KEY,
            forecast_date DATE NOT NULL,
            city VARCHAR NOT NULL,
            state VARCHAR NOT NULL,
            max_temp INTEGER NOT NULL,
            min_temp INTEGER NOT NULL);
          
[2023-06-18 21:00:43,977] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: airflow, Login: airflow, Password: XXXXXXXX, extra: None
[2023-06-18 21:00:43,985] {dbapi.py:180} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS master_weather (
            weather_id SERIAL PRIMARY KEY,
            forecast_date DATE NOT NULL,
            city VARCHAR NOT NULL,
            state VARCHAR NOT NULL,
            max_temp INTEGER NOT NULL,
            min_temp INTEGER NOT NULL);
          , parameters: None
[2023-06-18 21:00:43,989] {dbapi.py:186} INFO - Rows affected: -1
[2023-06-18 21:00:43,991] {postgres.py:73} INFO - NOTICE:  relation "master_weather" already exists, skipping

[2023-06-18 21:00:44,001] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=Postgres_airflow_connection_test_v01, task_id=create_weather_table, execution_date=20230617T000000, start_date=20230618T210043, end_date=20230618T210044
[2023-06-18 21:00:44,028] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-06-18 21:00:44,042] {local_task_job.py:146} INFO - Task exited with return code 0
